### ISSUE TITLE
[BUG] QR-code tags are not evaluated by the paperless server when using Paperparrot as uploader

### ISSUE THREAD

**Issue by nicolas-lang** [LeoKlaus/Paperparrot#255]
**Describe the bug**
QR-code tags are not evaluated by the paperless server when using Paperparrot as uploader.
When i scan/upload a document using Paperparrot it is processed and appears on the server with just the auto-assigned "New" tag. Downloading the very same document-pdf, then delting it from the server and uploading it from web-ui correctly assigns all QR-based tags. 

**To Reproduce**
1. Create tag `Bezahlt` in Web-UI, Set up paperless to allow QR codes as a Tag Source:
```yaml
    environment:
      PAPERLESS_CONSUMER_ENABLE_BARCODES: true
      PAPERLESS_CONSUMER_ENABLE_TAG_BARCODE: true
      PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING
      PAPERLESS_CONSUMER_BARCODE_UPSCALE: 2.0
      PAPERLESS_CONSUMER_BARCODE_DPI: 600
      PAPERLESS_CONSUMER_TAG_BARCODE_MAPPING: >
      {
            "T:BEZAHLT": "Bezahlt"
      }
```
2. Create a QR Code with text contents `T:BEZAHLT`

![Image](https://github.com/user-attachments/assets/2f66f022-6187-486c-996d-9f9bf8c3af84)

3. Physically attach the tag the document and scan it using Paperparrot.
4. After Processing: No (additional) tags  (Expected tag: `Bezahlt`)
5. Download document
6. Delete the document and empty recycle bin
7. Re-Upload document using web-ui
8. Document is processed and tags are present

**Expected behavior**
The document upload in Paperparrot should behave as uploading a document from the web ui. 
I would expect QR code based tags to be evaluated. 

**Screenshots**
*examples can be added on demand, but I would expect my description to be sufficient to reproduce*

**Environment:**
 - Device: iPad Pro 3. Gen
 - OS: iPadOS18.3.2
 - Version Paperparrot  2.4.3 (not payed yet)
 - Server Version: [2.15.1](https://github.com/paperless-ngx/paperless-ngx)

**Additional context**
I would assume that Paperparrot possibly pushed the document to the server using a different workflow from the web UI, and this somehow skips barcode evaluation as it is optional and not part of the basic workflow.
